# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc23b96f1a632e95a5c58586b9708631764c02cc29f0f8c54d7de1e0c39f614389b0367b6e560dcbceb3deaff1a9d9ae340e8c638fe959674522e6fb9880fe3f

test:
  secret_key_base: cd89913c5010ca1763f33dc6ccb15b04f87810bbf51d7b2d0421f86b7c28d15df94992410155c766e0ac5c294e6616a7da17dd8c758067e70a0fc658083d77c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
